package globalization

import (
	"github.com/axgle/mahonia"
)

var (
	enc = mahonia.NewDecoder("gbk")
	// 默认的GBK转换为UTF8的编码器
	EncoderGbkUtf8 = func (str string) string {
		return enc.ConvertString(str)
	}
)

const (
	LOCAL_NONE = Local(``) // 无
	LOCAL_af = Local(`af`) // 公用荷兰语
	LOCAL_af_ZA = Local(`af-ZA`) // 公用荷兰语 - 南非
	LOCAL_sq = Local(`sq`) // 阿尔巴尼亚
	LOCAL_sq_AL = Local(`sq-AL`) // 阿尔巴尼亚 -阿尔巴尼亚
	LOCAL_ar = Local(`ar`) // 阿拉伯语
	LOCAL_ar_DZ = Local(`ar-DZ`) // 阿拉伯语 -阿尔及利亚
	LOCAL_ar_BH = Local(`ar-BH`) // 阿拉伯语 -巴林
	LOCAL_ar_EG = Local(`ar-EG`) // 阿拉伯语 -埃及
	LOCAL_ar_IQ = Local(`ar-IQ`) // 阿拉伯语 -伊拉克
	LOCAL_ar_JO = Local(`ar-JO`) // 阿拉伯语 -约旦
	LOCAL_ar_KW = Local(`ar-KW`) // 阿拉伯语 -科威特
	LOCAL_ar_LB = Local(`ar-LB`) // 阿拉伯语 -黎巴嫩
	LOCAL_ar_LY = Local(`ar-LY`) // 阿拉伯语 -利比亚
	LOCAL_ar_MA = Local(`ar-MA`) // 阿拉伯语 -摩洛哥
	LOCAL_ar_OM = Local(`ar-OM`) // 阿拉伯语 -阿曼
	LOCAL_ar_QA = Local(`ar-QA`) // 阿拉伯语 -卡塔尔
	LOCAL_ar_SA = Local(`ar-SA`) // 阿拉伯语 - 沙特阿拉伯
	LOCAL_ar_SY = Local(`ar-SY`) // 阿拉伯语 -叙利亚共和国
	LOCAL_ar_TN = Local(`ar-TN`) // 阿拉伯语 -北非的共和国
	LOCAL_ar_AE = Local(`ar-AE`) // 阿拉伯语 - 阿拉伯联合酋长国
	LOCAL_ar_YE = Local(`ar-YE`) // 阿拉伯语 -也门
	LOCAL_hy = Local(`hy`) // 亚美尼亚
	LOCAL_hy_AM = Local(`hy-AM`) // 亚美尼亚的 -亚美尼亚
	LOCAL_az = Local(`az`) // Azeri
	LOCAL_az_AZ_Cyrl = Local(`az-AZ-Cyrl`) // Azeri-(西里尔字母的) 阿塞拜疆
	LOCAL_az_AZ_Latn = Local(`az-AZ-Latn`) // Azeri(拉丁文)- 阿塞拜疆
	LOCAL_eu = Local(`eu`) // 巴斯克
	LOCAL_eu_ES = Local(`eu-ES`) // 巴斯克 -巴斯克
	LOCAL_be = Local(`be`) // Belarusian
	LOCAL_be_BY = Local(`be-BY`) // Belarusian-白俄罗斯
	LOCAL_bg = Local(`bg`) // 保加利亚
	LOCAL_bg_BG = Local(`bg-BG`) // 保加利亚 -保加利亚
	LOCAL_ca = Local(`ca`) // 嘉泰罗尼亚
	LOCAL_ca_ES = Local(`ca-ES`) // 嘉泰罗尼亚 -嘉泰罗尼亚
	LOCAL_zh = Local(`zh`) // 中国
	LOCAL_zh_HK = Local(`zh-HK`) // 华 - 香港的 SAR
	LOCAL_zh_MO = Local(`zh-MO`) // 华 - 澳门的 SAR
	LOCAL_zh_CN = Local(`zh-CN`) // 华 -中国
	LOCAL_zh_CHS = Local(`zh-CHS`) // 华 (单一化)
	LOCAL_zh_SG = Local(`zh-SG`) // 华 -新加坡
	LOCAL_zh_TW = Local(`zh-TW`) // 华 -台湾
	LOCAL_zh_CHT = Local(`zh-CHT`) // 华 (传统的)
	LOCAL_hr = Local(`hr`) // 克罗埃西亚
	LOCAL_hr_HR = Local(`hr-HR`) // 克罗埃西亚 -克罗埃西亚
	LOCAL_cs = Local(`cs`) // 捷克
	LOCAL_cs_CZ = Local(`cs-CZ`) // 捷克 - 捷克
	LOCAL_da = Local(`da`) // 丹麦文
	LOCAL_da_DK = Local(`da-DK`) // 丹麦文 -丹麦
	LOCAL_div = Local(`div`) // Dhivehi
	LOCAL_div_MV = Local(`div-MV`) // Dhivehi-马尔代夫
	LOCAL_nl = Local(`nl`) // 荷兰
	LOCAL_nl_BE = Local(`nl-BE`) // 荷兰 -比利时
	LOCAL_nl_NL = Local(`nl-NL`) // 荷兰 - 荷兰
	LOCAL_en = Local(`en`) // 英国
	LOCAL_en_AU = Local(`en-AU`) // 英国 -澳洲
	LOCAL_en_BZ = Local(`en-BZ`) // 英国 -伯利兹
	LOCAL_en_CA = Local(`en-CA`) // 英国 -加拿大
	LOCAL_en_CB = Local(`en-CB`) // 英国 -加勒比海
	LOCAL_en_IE = Local(`en-IE`) // 英国 -爱尔兰
	LOCAL_en_JM = Local(`en-JM`) // 英国 -牙买加
	LOCAL_en_NZ = Local(`en-NZ`) // 英国 - 新西兰
	LOCAL_en_PH = Local(`en-PH`) // 英国 -菲律宾共和国
	LOCAL_en_ZA = Local(`en-ZA`) // 英国 - 南非
	LOCAL_en_TT = Local(`en-TT`) // 英国 - 千里达托贝哥共和国
	LOCAL_en_GB = Local(`en-GB`) // 英国 - 英国
	LOCAL_en_US = Local(`en-US`) // 英国 - 美国
	LOCAL_en_ZW = Local(`en-ZW`) // 英国 -津巴布韦
	LOCAL_et = Local(`et`) // 爱沙尼亚
	LOCAL_et_EE = Local(`et-EE`) // 爱沙尼亚的 -爱沙尼亚
	LOCAL_fo = Local(`fo`) // Faroese
	LOCAL_fo_FO = Local(`fo-FO`) // Faroese- 法罗群岛
	LOCAL_fa = Local(`fa`) // 波斯语
	LOCAL_fa_IR = Local(`fa-IR`) // 波斯语 -伊朗王国
	LOCAL_fi = Local(`fi`) // 芬兰语
	LOCAL_fi_FI = Local(`fi-FI`) // 芬兰语 -芬兰
	LOCAL_fr = Local(`fr`) // 法国
	LOCAL_fr_BE = Local(`fr-BE`) // 法国 -比利时
	LOCAL_fr_CA = Local(`fr-CA`) // 法国 -加拿大
	LOCAL_fr_FR = Local(`fr-FR`) // 法国 -法国
	LOCAL_fr_LU = Local(`fr-LU`) // 法国 -卢森堡
	LOCAL_fr_MC = Local(`fr-MC`) // 法国 -摩纳哥
	LOCAL_fr_CH = Local(`fr-CH`) // 法国 -瑞士
	LOCAL_gl = Local(`gl`) // 加利西亚
	LOCAL_gl_ES = Local(`gl-ES`) // 加利西亚 -加利西亚
	LOCAL_ka = Local(`ka`) // 格鲁吉亚州
	LOCAL_ka_GE = Local(`ka-GE`) // 格鲁吉亚州 -格鲁吉亚州
	LOCAL_de = Local(`de`) // 德国
	LOCAL_de_AT = Local(`de-AT`) // 德国 -奥地利
	LOCAL_de_DE = Local(`de-DE`) // 德国 -德国
	LOCAL_de_LI = Local(`de-LI`) // 德国 -列支敦士登
	LOCAL_de_LU = Local(`de-LU`) // 德国 -卢森堡
	LOCAL_de_CH = Local(`de-CH`) // 德国 -瑞士
	LOCAL_el = Local(`el`) // 希腊
	LOCAL_el_GR = Local(`el-GR`) // 希腊 -希腊
	LOCAL_gu = Local(`gu`) // Gujarati
	LOCAL_gu_IN = Local(`gu-IN`) // Gujarati-印度
	LOCAL_he = Local(`he`) // 希伯来
	LOCAL_he_IL = Local(`he-IL`) // 希伯来 -以色列
	LOCAL_hi = Local(`hi`) // 北印度语
	LOCAL_hi_IN = Local(`hi-IN`) // 北印度的 -印度
	LOCAL_hu = Local(`hu`) // 匈牙利
	LOCAL_hu_HU = Local(`hu-HU`) // 匈牙利的 -匈牙利
	LOCAL_is = Local(`is`) // 冰岛语
	LOCAL_is_IS = Local(`is-IS`) // 冰岛的 -冰岛
	LOCAL_id = Local(`id`) // 印尼
	LOCAL_id_ID = Local(`id-ID`) // 印尼 -印尼
	LOCAL_it = Local(`it`) // 意大利
	LOCAL_it_IT = Local(`it-IT`) // 意大利 -意大利
	LOCAL_it_CH = Local(`it-CH`) // 意大利 -瑞士
	LOCAL_ja = Local(`ja`) // 日本
	LOCAL_ja_JP = Local(`ja-JP`) // 日本 -日本
	LOCAL_kn = Local(`kn`) // 卡纳达语
	LOCAL_kn_IN = Local(`kn-IN`) // 卡纳达语 -印度
	LOCAL_kk = Local(`kk`) // Kazakh
	LOCAL_kk_KZ = Local(`kk-KZ`) // Kazakh-哈萨克
	LOCAL_kok = Local(`kok`) // Konkani
	LOCAL_kok_IN = Local(`kok-IN`) // Konkani-印度
	LOCAL_ko = Local(`ko`) // 韩国
	LOCAL_ko_KR = Local(`ko-KR`) // 韩国 -韩国
	LOCAL_ky = Local(`ky`) // Kyrgyz
	LOCAL_ky_KZ = Local(`ky-KZ`) // Kyrgyz-哈萨克
	LOCAL_lv = Local(`lv`) // 拉脱维亚
	LOCAL_lv_LV = Local(`lv-LV`) // 拉脱维亚的 -拉脱维亚
	LOCAL_lt = Local(`lt`) // 立陶宛
	LOCAL_lt_LT = Local(`lt-LT`) // 立陶宛 -立陶宛
	LOCAL_mk = Local(`mk`) // 马其顿
	LOCAL_mk_MK = Local(`mk-MK`) // 马其顿 -FYROM
	LOCAL_ms = Local(`ms`) // 马来
	LOCAL_ms_BN = Local(`ms-BN`) // 马来 -汶莱
	LOCAL_ms_MY = Local(`ms-MY`) // 马来 -马来西亚
	LOCAL_mr = Local(`mr`) // 马拉地语
	LOCAL_mr_IN = Local(`mr-IN`) // 马拉地语 -印度
	LOCAL_mn = Local(`mn`) // 蒙古
	LOCAL_mn_MN = Local(`mn-MN`) // 蒙古 -蒙古
	LOCAL_no = Local(`no`) // 挪威
	LOCAL_nb_NO = Local(`nb-NO`) // 挪威 (Bokm?l) - 挪威
	LOCAL_nn_NO = Local(`nn-NO`) // 挪威 (Nynorsk)- 挪威
	LOCAL_pl = Local(`pl`) // 波兰
	LOCAL_pl_PL = Local(`pl-PL`) // 波兰 -波兰
	LOCAL_pt = Local(`pt`) // 葡萄牙
	LOCAL_pt_BR = Local(`pt-BR`) // 葡萄牙 -巴西
	LOCAL_pt_PT = Local(`pt-PT`) // 葡萄牙 -葡萄牙
	LOCAL_pa = Local(`pa`) // Punjab 语
	LOCAL_pa_IN = Local(`pa-IN`) // Punjab 语 -印度
	LOCAL_ro = Local(`ro`) // 罗马尼亚语
	LOCAL_ro_RO = Local(`ro-RO`) // 罗马尼亚语 -罗马尼亚
	LOCAL_ru = Local(`ru`) // 俄国
	LOCAL_ru_RU = Local(`ru-RU`) // 俄国 -俄国
	LOCAL_sa = Local(`sa`) // 梵文
	LOCAL_sa_IN = Local(`sa-IN`) // 梵文 -印度
	LOCAL_sr_SP_Cyrl = Local(`sr-SP-Cyrl`) // 塞尔维亚 -(西里尔字母的) 塞尔
	LOCAL_sr_SP_Latn = Local(`sr-SP-Latn`) // 塞尔维亚 (拉丁文)- 塞尔维亚共
	LOCAL_sk = Local(`sk`) // 斯洛伐克
	LOCAL_sk_SK = Local(`sk-SK`) // 斯洛伐克 -斯洛伐克
	LOCAL_sl = Local(`sl`) // 斯洛文尼亚
	LOCAL_sl_SI = Local(`sl-SI`) // 斯洛文尼亚 -斯洛文尼亚
	LOCAL_es = Local(`es`) // 西班牙
	LOCAL_es_AR = Local(`es-AR`) // 西班牙 -阿根廷
	LOCAL_es_BO = Local(`es-BO`) // 西班牙 -玻利维亚
	LOCAL_es_CL = Local(`es-CL`) // 西班牙 -智利
	LOCAL_es_CO = Local(`es-CO`) // 西班牙 -哥伦比亚
	LOCAL_es_CR = Local(`es-CR`) // 西班牙 - 哥斯达黎加
	LOCAL_es_DO = Local(`es-DO`) // 西班牙 - 多米尼加共和国
	LOCAL_es_EC = Local(`es-EC`) // 西班牙 -厄瓜多尔
	LOCAL_es_SV = Local(`es-SV`) // 西班牙 - 萨尔瓦多
	LOCAL_es_GT = Local(`es-GT`) // 西班牙 -危地马拉
	LOCAL_es_HN = Local(`es-HN`) // 西班牙 -洪都拉斯
	LOCAL_es_MX = Local(`es-MX`) // 西班牙 -墨西哥
	LOCAL_es_NI = Local(`es-NI`) // 西班牙 -尼加拉瓜
	LOCAL_es_PA = Local(`es-PA`) // 西班牙 -巴拿马
	LOCAL_es_PY = Local(`es-PY`) // 西班牙 -巴拉圭
	LOCAL_es_PE = Local(`es-PE`) // 西班牙 -秘鲁
	LOCAL_es_PR = Local(`es-PR`) // 西班牙 - 波多黎各
	LOCAL_es_ES = Local(`es-ES`) // 西班牙 -西班牙
	LOCAL_es_UY = Local(`es-UY`) // 西班牙 -乌拉圭
	LOCAL_es_VE = Local(`es-VE`) // 西班牙 -委内瑞拉
	LOCAL_sw = Local(`sw`) // Swahili
	LOCAL_sw_KE = Local(`sw-KE`) // Swahili-肯尼亚
	LOCAL_sv = Local(`sv`) // 瑞典
	LOCAL_sv_FI = Local(`sv-FI`) // 瑞典 -芬兰
	LOCAL_sv_SE = Local(`sv-SE`) // 瑞典 -瑞典
	LOCAL_syr = Local(`syr`) // Syriac
	LOCAL_syr_SY = Local(`syr-SY`) // Syriac-叙利亚共和国
	LOCAL_ta = Local(`ta`) // 坦米尔
	LOCAL_ta_IN = Local(`ta-IN`) // 坦米尔 -印度
	LOCAL_tt = Local(`tt`) // Tatar
	LOCAL_tt_RU = Local(`tt-RU`) // Tatar-俄国
	LOCAL_te = Local(`te`) // Telugu
	LOCAL_te_IN = Local(`te-IN`) // Telugu-印度
	LOCAL_th = Local(`th`) // 泰国
	LOCAL_th_TH = Local(`th-TH`) // 泰国 -泰国
	LOCAL_tr = Local(`tr`) // 土耳其语
	LOCAL_tr_TR = Local(`tr-TR`) // 土耳其语 -土耳其
	LOCAL_uk = Local(`uk`) // 乌克兰
	LOCAL_uk_UA = Local(`uk-UA`) // 乌克兰 -乌克兰
	LOCAL_ur = Local(`ur`) // Urdu
	LOCAL_ur_PK = Local(`ur-PK`) // Urdu-巴基斯坦
	LOCAL_uz = Local(`uz`) // Uzbek
	LOCAL_uz_UZ_Cyrl = Local(`uz-UZ-Cyrl`) // Uzbek-(西里尔字母的) 乌兹别克
	LOCAL_uz_UZ_Latn = Local(`uz-UZ-Latn`) // Uzbek(拉丁文)- 乌兹别克斯坦
	LOCAL_vi = Local(`vi`) // 越南
	LOCAL_vi_VN = Local(`vi-VN`) // 越南 -越南

)